import { createContext, useContext } from "react";

export const DataContext = createContext({
  AllProductData: [
    {
      id: "men1",
      category: "men",
      brand: "PUMA",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "2999",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "men2",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "599",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "men3",
      category: "men",
      brand: "SHIVAM",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "499",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "men4",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "199",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men5",
      category: "men",
      brand: "PUMA",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "745",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men6",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men7",
      category: "men",
      brand: "PUMA",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men8",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men9",
      category: "men",
      brand: "PUMA",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men10",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men11",
      category: "men",
      brand: "PUMA",
      productName: "Pack of 2 Mens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "men12",
      category: "men",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "new1",
      category: "new",
      brand: "PUMA",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "399",
      OriginalPrice: "2999",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new2",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new3",
      category: "new",
      brand: "SHIVAM",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new4",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new5",
      category: "new",
      brand: "PUMA",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new6",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new7",
      category: "new",
      brand: "PUMA",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new8",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new9",
      category: "new",
      brand: "PUMA",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new10",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new11",
      category: "new",
      brand: "PUMA",
      productName: "Pack of 2 news Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "new12",
      category: "new",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: true,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "women1",
      category: "women",
      brand: "PUMA",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "399",
      OriginalPrice: "2999",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "women2",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "women3",
      category: "women",
      brand: "SHIVAM",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
      favorite: false,
    },
    {
      id: "women4",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women5",
      category: "women",
      brand: "PUMA",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women6",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women7",
      category: "women",
      brand: "PUMA",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women8",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women9",
      category: "women",
      brand: "PUMA",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women10",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women11",
      category: "women",
      brand: "PUMA",
      productName: "Pack of 2 womens Solid Color Track Pants",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt1",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
    {
      id: "women12",
      category: "women",
      brand: "NIKE",
      productName: "Jeans Pant",
      SellingPrice: "299",
      OriginalPrice: "499",
      hover: false,
      verified: false,
      alt: "alt2",
      imgUrl:
        "https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70",
    },
  ],
});

export const useData = () => {
  return useContext(DataContext);
};
export const DataProvider = DataContext.Provider;
