export const Menswear = [
    {
        id: 'men1',
        category: 'Men',
        brand: 'PUMA',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '399',
        OrignalPrice: '2999',
        hover: false,
        verified: true,
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
        favorite:true,
    },
    {
        id: 'men2',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: false,
        verified: true,
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
        favorite:false,

    },
    {
        id: 'men3',
        category: 'Men',
        brand: 'SHIVAM',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: false,
        verified: false,
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
        favorite:false,

    },
    {
        id: 'men4',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men5',
        category: 'Men',
        brand: 'PUMA',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men6',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men7',
        category: 'Men',
        brand: 'PUMA',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men8',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men9',
        category: 'Men',
        brand: 'PUMA',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men10',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men11',
        category: 'Men',
        brand: 'PUMA',
        productName: 'Pack of 2 Mens Solid Color Tarck Pants',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt1',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },
    {
        id: 'men12',
        category: 'Men',
        brand: 'NIKE',
        productName: 'Jeans Pant',
        SellingPrice: '299',
        OrignalPrice: '499',
        hover: 'false',
        verified: 'true',
        alt: 'alt2',
        imgUrl: 'https://rukminim2.flixcart.com/image/612/612/xif0q/track-pant/5/d/y/xxl-av104sl-combo-avolt-original-imagjgbwkggfp52e.jpeg?q=70',
    },


]